name: Keep Render App Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:        # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          echo "Pinging Render app..."
          curl -s -o /dev/null -w "%{http_code}" https://quizv2-wq0n.onrender.com/
